"""
CCTV Detection Event Model.
Captures confirmed civic defect telemetry generated by the independent CCTV AI service.
Stored separately from citizen complaints until reviewed by a municipal officer.
"""

from datetime import datetime, timezone
import json
from sqlalchemy import Column, String, Integer, Float, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from ..database.session import Base

class CctvEvent(Base):
    __tablename__ = "cctv_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(String(100), unique=True, nullable=False, index=True)
    event_type = Column(String(50), default="POTHOLE_DETECTED", nullable=False)
    camera_id = Column(String(50), nullable=False, index=True)
    source_video = Column(String(120), nullable=True)
    confidence = Column(Float, nullable=False)
    peak_confidence = Column(Float, nullable=True)
    event_score = Column(Float, nullable=True)
    severity = Column(String(20), default="MEDIUM", nullable=False)
    status = Column(String(30), default="PENDING_REVIEW", nullable=False, index=True)
    # PENDING_REVIEW, VERIFIED, DISMISSED, CONVERTED
    timestamp_video = Column(String(30), nullable=True)
    frame_number = Column(Integer, nullable=True)
    bbox_json = Column(Text, nullable=True)
    persistence_seconds = Column(Float, nullable=True)
    supporting_detections = Column(Integer, nullable=True)
    evidence_image_path = Column(String(255), nullable=True)
    evidence_image_url = Column(String(255), nullable=True)
    address = Column(String(255), nullable=True)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    reviewed_by_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    review_notes = Column(Text, nullable=True)
    complaint_id = Column(String(30), ForeignKey("complaints.id"), nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc), nullable=False)

    reviewer = relationship("User", foreign_keys=[reviewed_by_id])
    complaint = relationship("Complaint", foreign_keys=[complaint_id])

    @property
    def bbox(self):
        if not self.bbox_json:
            return None
        try:
            return json.loads(self.bbox_json)
        except Exception:
            return None
