from .classification_prompt import CLASSIFICATION_SYSTEM_PROMPT, CLASSIFICATION_USER_TEMPLATE
from .severity_prompt import SEVERITY_SYSTEM_PROMPT, SEVERITY_USER_TEMPLATE
from .department_prompt import DEPARTMENT_SYSTEM_PROMPT, DEPARTMENT_USER_TEMPLATE

__all__ = [
    "CLASSIFICATION_SYSTEM_PROMPT", "CLASSIFICATION_USER_TEMPLATE",
    "SEVERITY_SYSTEM_PROMPT", "SEVERITY_USER_TEMPLATE",
    "DEPARTMENT_SYSTEM_PROMPT", "DEPARTMENT_USER_TEMPLATE"
]
