"""
Complaint Pydantic Schemas
"""

from datetime import datetime
from typing import Optional, List, Dict, Any, Union
from pydantic import BaseModel

class EvidenceSchema(BaseModel):
    id: Optional[int] = None
    type: str = "image"
    file_url: str
    description: Optional[str] = None
    ai_analysis: Optional[str] = None

    class Config:
        from_attributes = True

class ComplaintHistorySchema(BaseModel):
    id: int
    old_status: Optional[str] = None
    new_status: str
    changed_by: Optional[str] = None
    remarks: Optional[str] = None
    timestamp: datetime

    class Config:
        from_attributes = True

class AgentActionSchema(BaseModel):
    id: Optional[int] = None
    agent_name: str
    action: str
    input_summary: Optional[str] = None
    output_summary: Optional[str] = None
    timestamp: datetime

    class Config:
        from_attributes = True

class EscalationSchema(BaseModel):
    id: int
    reason: str
    level: int
    created_at: datetime
    resolved_at: Optional[datetime] = None

    class Config:
        from_attributes = True

class ComplaintAnalyzeRequest(BaseModel):
    text: Optional[str] = None
    voice_transcription: Optional[str] = None
    address: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    image_url: Optional[str] = None

class ComplaintSubmitRequest(BaseModel):
    id: Optional[str] = None  # CSXXXX or autogenerated
    title: Optional[str] = None
    category: str
    issue_type: Optional[str] = None
    description: str
    generated_complaint: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    address: Optional[str] = None
    severity: str = "MEDIUM"
    department_id: Optional[Union[int, str]] = None
    ai_confidence: Optional[float] = 0.90
    severity_reason: Optional[str] = None
    grounded_explanation: Optional[str] = None
    recommended_action: Optional[str] = None
    image_url: Optional[str] = None
    evidence_urls: Optional[List[str]] = []
    decision_trace: Optional[List[Dict[str, Any]]] = []

class ComplaintStatusUpdate(BaseModel):
    status: str
    remarks: Optional[str] = None
    department_id: Optional[int] = None

class ComplaintFollowupRequest(BaseModel):
    remarks: Optional[str] = "Citizen requested status follow-up"

class ComplaintEscalateRequest(BaseModel):
    reason: str = "Complaint has remained unresolved beyond SLA threshold"
    level: Optional[int] = 1

class ComplaintResponse(BaseModel):
    id: str
    citizen_id: Optional[int] = None
    category: str
    issue_type: Optional[str] = None
    description: str
    generated_complaint: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    address: Optional[str] = None
    severity: str
    status: str
    department_id: Optional[int] = None
    department_name: Optional[str] = None
    assigned_officer_id: Optional[int] = None
    assigned_officer_name: Optional[str] = None
    assigned_officer_phone: Optional[str] = None
    officer_distance_km: Optional[float] = None
    officer_eta_minutes: Optional[int] = None
    cluster_id: Optional[str] = None
    is_duplicate: Optional[int] = 0
    ai_confidence: Optional[float] = None
    severity_reason: Optional[str] = None
    grounded_explanation: Optional[str] = None
    recommended_action: Optional[str] = None
    follow_up_count: int = 0
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True

class ComplaintDetailResponse(ComplaintResponse):
    evidence_list: List[EvidenceSchema] = []
    history: List[ComplaintHistorySchema] = []
    agent_actions: List[AgentActionSchema] = []
    escalations: List[EscalationSchema] = []
